// <auto-generated />
namespace RZUEP_CA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dzien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dzien));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051513347_dzien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
